### ISSUE TITLE
improved support for nvidia

### ISSUE THREAD

**Issue by lestofante** [lestofante/ksysguard-gpu#11]
This is a discussion for pull request #6 

First of all thanks @pohzhiee very much for your work, I completely missed all github notification for this project.

I am having a bit of hard time to see the diff as github cannot understand when is code or indentation changes.

> run() function is now an infinite loop due to the thread terminating
after the subprocess finished, which results in undesired behaviour

well, that mean if you dont have nvidia you will have a thread always running; I am changing it to quit on a FileNotFound exception (the executable is missing).
Do you have issue on the nvidia-sli crashing?

> Removed power draw data due to some cards not supporting (GTX 1050TI)

I fear if we remove parameter here and there when not supported, we will end up without parameter. I dont have an nvidia so it makes hard to me to play around with the command line, but i think maybe we can make it output all supported field, and extrapolate them from the header? would be nice to have some output dump so I can work on it (and maybe set up some test)

to speed up the process I am going to include the other changes directly in develop, drop the PR, and we can track the nvidia improvements here so the discussion does not get lost

**Comment by lestofante** [comment]
@pohzhiee according to nvidia-smi docs, the missing field should be output as "n/a", is this the behavior you are getting?

**Comment by pohzhiee** [comment]
![image](https://user-images.githubusercontent.com/22704923/71781757-2f084280-300d-11ea-8da5-ddd414d6fddd.png)

The not supported fields are literally written [Not Supported]

> Do you have issue on the nvidia-sli crashing?

I am not sure how it is on AMD, but for nvidia-smi it just prints out the current information and then terminates, it is not a continuously running process like top. Since AMD's executable to get the information is called radeontop, I suspect it runs like top.

**Comment by lestofante** [comment]
> The not supported fields are literally written [Not Supported]

this is actually quite good, i can just ingnore them

> nvidia-smi it just prints out the current information

the argument -l1 is passed, that make the output loop at 1Hz rate, so that should not be an issue

**Comment by pohzhiee** [comment]
> the argument -l1 is passed, that make the output loop at 1Hz rate, so that should not be an issue

Ah it seems I was missing a space. It was supposed to be `-l 1`. Then it works as expected

**Comment by lestofante** [comment]
good :)

can you please give me a text dump of the nvidia-smi command, so i can make sure to correctly handle the `not supported` fields?
