### ISSUE TITLE
Connection refused Radeontop

### ISSUE THREAD

**Issue by Extarys** [lestofante/ksysguard-gpu#15]
Radeontop works. I'm also in the `video` group.

```
$ sudo /usr/bin/gpuStatsServer.py
intel_gpu_top: executable not found
radeontop: found and running
nvidia-smi: executable not found
intel_gpu_top: terminated
nvidia-smi: terminated
```

In another window I tried:
```
$ netcat 127.0.0.1 3112 -v
netcat: connect to 127.0.0.1 port 3112 (tcp) failed: Connection refused
```
I get `Connection to 127.0.0.1 refused` when trying to add the host in ksysguard. I tried running the python software directly same issue.

Can someone tell me what I missed?

**Comment by lestofante** [comment]
very strange, can you please look at the status of the service? you can run `systemctl status gpuStatsServer.service`

**Comment by Extarys** [comment]
Oh sorry, since microsoft bought Github I dont hang much here anymore and missed the notification.

I changed OS for now as the KDE one I tried was too buggy. I'll close for now and retest once I have reinstalled everything properly :)

Cheers!
