### ISSUE TITLE
Error: Host GPU Not found

### ISSUE THREAD

**Issue by QuakeString** [lestofante/ksysguard-gpu#16]
I've installed ksysguard-gup from AUR, ( I'm running Mnajaro latest KDE (Stable)
I get Error "Host GPU not found"
![Screenshot_20200518_092740](https://user-images.githubusercontent.com/5375918/82170219-d2396480-98e9-11ea-921a-bb1eab502b46.png)

![Screenshot_20200518_092425](https://user-images.githubusercontent.com/5375918/82170148-a3bb8980-98e9-11ea-9972-ecfef45e55f0.png)
![Screenshot_20200518_092338](https://user-images.githubusercontent.com/5375918/82170159-a8803d80-98e9-11ea-9fdc-e40dd72c8138.png)

**Comment by lestofante** [comment]
Host should be 127.0.0.1

**Comment by QuakeString** [comment]
Sorry, my bad,
I did mistake to show you wrong photo.
Here is right photo of error
![Screenshot_20200522_083903](https://user-images.githubusercontent.com/5375918/82624028-a8dd4900-9c07-11ea-8c17-c06be71e7407.png)
![Screenshot_20200522_083852](https://user-images.githubusercontent.com/5375918/82624036-ac70d000-9c07-11ea-8bf0-c76590346be2.png)
![Screenshot_20200522_083823](https://user-images.githubusercontent.com/5375918/82624055-b8f52880-9c07-11ea-8448-b28bd47f2d6c.png)
