### ISSUE TITLE
Error : Connection 127.0.0.1 refused 

### ISSUE THREAD

**Issue by QuakeString** [lestofante/ksysguard-gpu#17]
I'm facing this problem
Connection 127.0.0.1 refused 
manjaro KDE 5.18
here is video demonstrated the error.
https://drive.google.com/file/d/1v5mTjJdPthZZOtJ2IlYtlvABtB3AK_Ts/view?usp=sharing

**Comment by lestofante** [comment]
is the ksysguard-gpu service running?
check with `systemctl status ksysguard-gpu`

**Comment by QuakeString** [comment]
It did worked, ksysguard-gpu service was not active.
there is so many sensor, not sure which one for what.
![Screenshot_20200528_092511](https://user-images.githubusercontent.com/5375918/83093371-513a5400-a0c5-11ea-880d-786280c5833c.png)

**Comment by lestofante** [comment]
yeah, gpu has different engines inside, basically dedicated processor for specific job.

Generally to have an overview add everything with a % symbol in one chart, and the RAM usage in MB in another and temp in the last one.

Later with time you will see what engine you care about depending on the application you are using.

Closed as fixed
