### ISSUE TITLE
Log in systemd journal

### ISSUE THREAD

**Issue by luigir-it** [lestofante/ksysguard-gpu#18]
Hello.
I just read the journal log, and over 90% of the lines are like this
`ksysguard-gpu.py[599]: nvidia-smi: found and running`
Last time I cleaned the log was on november, now it's 3gb. Most of that are the same lines written above.
Is it normal? Is there a way to stop this? Thanks.

**Comment by luigir-it** [comment]
Solved by adding StandardOutput=null to the service (inside [Service])
Remember to reload the service (or reboot) after the modification

**Comment by lestofante** [comment]
thanks for reporting, it actually mean there is a deeper problem, you are using the nvidia reporting and looks like it is crashing/exiting often (maybe every output?). Will look into it

**Comment by lestofante** [comment]
caused by #11 , fixed
