### ISSUE TITLE
intel-gpu-tools parsing exception

### ISSUE THREAD

**Issue by alexdaguy** [lestofante/ksysguard-gpu#21]
This problem that I have is kind of similar to #12 . I was not able to connect via ksysguard, so i tried to run the script `ksysguard-gpu.py` to see what was going on. This is the log:

```
radeontop: executable not found
radeontop: process stopped
nvidia-smi: executable not found
Traceback (most recent call last):
nvidia-smi: process stopped
  File "/home/alexdaguy/Documents/ksysguard-gpu/src/ksysguard-gpu.py", line 191, in run
    self.parser.parseLine(line)
  File "/home/alexdaguy/Documents/ksysguard-gpu/src/ksysguard-gpu.py", line 55, in parseLine
    print( "Intel parse line error: I am expecting " + str(len(indexNames)) + " parameter but I got " + str(len(parameters)) + " parsed line is " + line )
NameError: name 'indexNames' is not defined
intel_gpu_top: exception while parsing the line, please report the bug b'  25   25       72  93    6.87   0   0    0.00   0   0    0.00   0   0    0.00   0   0    0.00   0   0 \n'
Traceback (most recent call last):
  File "/home/alexdaguy/Documents/ksysguard-gpu/src/ksysguard-gpu.py", line 191, in run
    self.parser.parseLine(line)
  File "/home/alexdaguy/Documents/ksysguard-gpu/src/ksysguard-gpu.py", line 55, in parseLine
    print( "Intel parse line error: I am expecting " + str(len(indexNames)) + " parameter but I got " + str(len(parameters)) + " parsed line is " + line )
NameError: name 'indexNames' is not defined
radeontop: terminated
nvidia-smi: terminated
intel_gpu_top: exception while parsing the line, please report the bug b'  25   26       66  93    6.76   0   0    0.00   0   0    0.00   0   0    0.00   0   0    0.00   0   0 \n'
```
So this is not working for the Intel GPU.

Looking at the script, it seems like it was already not going to work, as the length of the header was not the same as the parameters.
Headers:
`['fReq', 'fAtt', 'irq/s', 'rc6.%', 'RCS.%', 'RCS.se', 'RCS.wa', 'BCS.%', 'BCS.se', 'BCS.wa', 'VCS.%', 'VCS.se', 'VCS.wa', 'VECS.%', 'VECS.se', 'VECS.wa']` (length 16)
Parameters: `['41', '41', '75', '96', '3.74', '0', '0', '0.00', '0', '0', '0.00', '0', '0', '0.00', '0', '0', '0.00', '0', '0']` (length 19)
After looking at intel_gpu_top's output, It seems that the script doesn't handle headers ending in `/1` and only those ending in `/0`. Adding a handle for it that gives the headers a different name seems to resolve the issue. However, there could be more numbers such as `/2` on some systems, but I don't know how it works, which is why I would look further into it before patching this.

But the part of the script that wants to report the parsing problem seems to be broken as well, as `indexNames` does not appear anywhere else in the script. These both seem to be a simple fix though.

Sorry if this is a bad issue, I am new to GitHub collaboration

**Comment by lestofante** [comment]
Hi, very late answer but I think i managed to fix the problem; can you test the script in develop?
If you would add the first few line from "intel_gpu_top -l" ill add it to the unit test.
Also notice there is now a Json option, but not sure how to feed to python a "streaming" json

**Comment by joaolbasto** [comment]
Not sure if this is what you needed, but i ran the test script came back with no errors follows also output of the requested command.

```
sudo python test_intel.py 
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK


$ sudo intel_gpu_top -l
 Freq MHz      IRQ RC6     Power W     IMC MiB/s           RCS/0           BCS/0           VCS/0          VECS/0 
 req  act       /s   %   gpu   pkg     rd     wr       %  se  wa       %  se  wa       %  se  wa       %  se  wa 
   0    0        0   0  0.00  0.00   1700    105   99.53   0   0    0.00   0   0    0.00   0   0    0.00   0   0 
 223  223      412  48  0.43  3.98   2526   1076   43.06   0   0    0.00   0   0    0.00   0   0    0.00   0   0 

```

**Comment by lestofante** [comment]
thanks, but `test_intel.py ` is the unit test, you can just run the normal application (i also merged it with master, btw).
The second command was perfect, and actually I found out some more bug in the parser! you can test the latest develop and let me know if this work for you!

**Comment by joaolbasto** [comment]
Hello,

Afraid no joy

```
src]$ git branch
* develop
  master

src]$ sudo ksysguard-gpu.py
radeontop: executable not found
radeontop: process stopped
nvidia-smi: executable not found
nvidia-smi: process stopped
intel_gpu_top: found and running
nvidia-smi: terminated
radeontop: terminated


src]$` sudo python test_intel.py
.F
======================================================================
FAIL: test_txt2 (__main__.TestIntelParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sbasto/.tmp/ksysguard-gpu/src/test_intel.py", line 67, in test_txt2
    self.assertEqual(expected, allGpu)
AssertionError: {'Intel.0.fReq': '223', 'Intel.0.fAtt': '2[424 chars] '0'} != {}
+ {}
- {'Intel.0.BCS.%': '0.00',
-  'Intel.0.BCS.se': '0',
-  'Intel.0.BCS.wa': '0',
-  'Intel.0.RCS.%': '43.06',
-  'Intel.0.RCS.se': '0',
-  'Intel.0.RCS.wa': '0',
-  'Intel.0.VCS.%': '0.00',
-  'Intel.0.VCS.se': '0',
-  'Intel.0.VCS.wa': '0',
-  'Intel.0.VECS.%': '0.00',
-  'Intel.0.VECS.se': '0',
-  'Intel.0.VECS.wa': '0',
-  'Intel.0.fAtt': '223',
-  'Intel.0.fReq': '223',
-  'Intel.0.gpu': '0.43',
-  'Intel.0.irq/s': '412',
-  'Intel.0.pkg': '3.98',
-  'Intel.0.rc6.%': '48',
-  'Intel.0.rd': '2526',
-  'Intel.0.wr': '1076'}

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=1)

```

**Comment by lestofante** [comment]
can you try to pull? seems like you have an older version
