### ISSUE TITLE
Installation script does not install all the required file

### ISSUE THREAD

**Issue by lestofante** [lestofante/ksysguard-gpu#24]
as per https://github.com/lestofante/ksysguard-gpu/issues/23#issuecomment-940809219

**Comment by joaolbasto** [comment]
This caused the Systemctl to not be able to start.

_ExecStart=/usr/bin/ksysguard-gpu.zip_

the ZIP file is not executable 

```
bin]$ sudo /usr/bin/ksysguard-gpu.zip
sudo: /usr/bin/ksysguard-gpu.zip: command not found


-rw-r--r-- 1 root root   4363 Oct 12 12:33 ksysguard-gpu.zip
```


attempted to give it the x tag to execute, but its still not working

```
 bin]$ sudo chmod +x ksysguard-gpu.zip

/usr/bin/ksysguard-gpu.zip: /usr/bin/ksysguard-gpu.zip: cannot execute binary file

```

**Comment by lestofante** [comment]
you dont need to make it executable, you just need to feed the zup to python, it will fuind the __main__.py inside and execute it:
`sudo python /usr/bin/ksysguard-gpu.zip` (make sure you actually need sudo, in most distro you dont)

**Comment by joaolbasto** [comment]
thanks, guess if i just had python to the ExecStart in the .service file, it should go back to working.

```
[Unit]
Description=Collect GPU stats
After=network.target

[Service]
ExecStart=python /usr/bin/ksysguard-gpu.zip
Restart=on-failure

[Install]
WantedBy=default.target

 bin]$ sudo systemctl daemon-reload
 bin]$ sudo systemctl start ksysguard-gpu.service
 bin]$ sudo systemctl status ksysguard-gpu.service
● ksysguard-gpu.service - Collect GPU stats
     Loaded: loaded (/etc/systemd/system/ksysguard-gpu.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2021-10-12 13:10:28 BST; 4s ago
   Main PID: 70641 (python)
      Tasks: 3 (limit: 18817)
     Memory: 6.2M
        CPU: 89ms
     CGroup: /system.slice/ksysguard-gpu.service
             ├─70641 python /usr/bin/ksysguard-gpu.zip
             └─70643 intel_gpu_top -l

Oct 12 13:10:28 ws001 systemd[1]: Started Collect GPU stats.
```


Regarding sudo, afraid if i don't sudo the output just repeats this lines in a loop, even with my user in the video group

intel_gpu_top: process stopped
intel_gpu_top: found and running
intel_gpu_top: process stopped
intel_gpu_top: found and running

**Comment by lestofante** [comment]
> Regarding sudo, afraid if i don't sudo the output just repeats this lines in a loop, even with my user in the video group

ah ok, i know there are ways but i dont have time to investigate right now

> thanks, guess if i just had python to the ExecStart in the .service file, it should go back to working.

whops my bad, fixed this too. if this works fine, then you can close this issue :)
