### ISSUE TITLE
Doesn't let me connect to the script

### ISSUE THREAD

**Issue by Akrai** [lestofante/ksysguard-gpu#3]
I don't know what is wrong, i installed using the script, the systemd unit is running with ok signal, in ksys i try to connect to the service in 127.0.0.1 3112 but denied, i tried to stop the systemd unit and run manually the script as root (i have an intel hd graphic) no error from the intel function, error from and and nvidia, but still cant connect to it, i tried to add me and root to video group (is what ls -la /dev/dri/card0 returns) and still denied... what could be wrong?

**Comment by Akrai** [comment]
Oh and by the way, bug in the uninstall script: it tries to rm /usr/bin/gpuServer.py, which doesn't exist

**Comment by lestofante** [comment]
Interesting. you can use netcat or telnet to connect to the port 3112 and send commands.

"monitors" should return the list of all available sensors,
and the name of the sensor should return the value.

about the script ill fix it tomorrow :)

**Comment by Akrai** [comment]
netcat 127.0.0.1 3112 -v
localhost.localdomain [127.0.0.1] 3112 (ksysguard): Connection denied (my translation from spanish)

**Comment by Akrai** [comment]
server_address = ('localhost', 3112)
print ('starting up on %s port %s' % server_address)
server.bind(server_address)

executing the .py in the terminal should output that message right?
But i only get:
./gpuStatsServer.py 
nvidia-smi is not currently supported
radeontop process has died! probably is not installed, or need root
intel_gpu_top process has died! probably is not installed, or need root
and thats it, no ending

**Comment by lestofante** [comment]
ah bravo!
we have a little loop to make sure you get some info from your GPU.
In your case, both Intel and AMD process have died, so you will never have info available.

Try to manually run, as superuser, `intel_gpu_top -l` and post the output

**Comment by Akrai** [comment]
https://i.imgur.com/Q82O0Ag.png

**Comment by Akrai** [comment]
Also, maybe useful for the data parsing, every few lines it outputs again the heading text of the columns:
https://i.imgur.com/8JmrQOJ.png

**Comment by lestofante** [comment]
ok, then try to run the script (of course as superuser) and check if start properly (you should get only amd "crashing"), then if it works netcat, then if it work restart the service. Pay attention to the journal to see if the output match the output we expect.

> every few lines it outputs again the heading text of the columns:

yes, is all handled properly, sorta (i expect your filed to have tte same name as mine:
['fReq', 'fAtt', 'irq/s', 'rc6%', 'Watt', 'rcs%', 'rcsSe', 'rcsWa', 'bcs%', 'bcsSe', 'bcsWa', 'vcs%', 'vcsSe', 'vcsWa', 'vecs%', 'vecsSe', 'vecsWa'])

**Comment by Akrai** [comment]
i get the same :(
https://i.imgur.com/qSd3LfR.png
shouldn't i get in the script output a "starting up on %s port %s"?

**Comment by lestofante** [comment]
yes you should get it, but only if the intel command send data.
can you save the output of the intel_gpu_top -l to a file with intel_gpu_top -l > log.txt and attach it here? ill try to take a look as soon as i get time

**Comment by Akrai** [comment]
there is no rush, don't worry, thanks
[log.txt](https://github.com/lestofante/ksysguard-gpu/files/3654620/log.txt)

**Comment by lestofante** [comment]
i see the rpobelm, your output is different from mine, it add IMC MiB/s, and because i am expecting an hardcoded list of value, it would not work. Well, guess i will need to fix it with some patience to make the list of field dynamic or force the command to output what we want

**Comment by lestofante** [comment]
This issue should be fixed, please checkout master, tag 0.2, let me know if all is good for you

**Comment by Akrai** [comment]
the uninstall script still has the bug, it should say:
rm /usr/bin/gpuStatsServer.py

**Comment by Akrai** [comment]
https://i.imgur.com/y9cG0UK.png
(i've done this without using the install script, just to avoid running the script while it is already running by the systemd unit, so the script is there by me cp it and chmod +x it just before the screenshot)

**Comment by Akrai** [comment]
luckily i just thought about giving it a try in ksysguard anyway, and it works!!!
https://i.imgur.com/ligt88N.png

**Comment by lestofante** [comment]
> https://i.imgur.com/y9cG0UK.png
> (i've done this without using the install script, just to avoid running the script while it is already running by the systemd unit, so the script is there by me cp it and chmod +x it just before the screenshot)

in this one the error is "address already in use", it mean you already had one instance running

**Comment by Akrai** [comment]
Lastly, if you want to provide an intel only tab, here you have it, i also modified the hscale to 3, but as you want, i just prefer to have a bigger time resolution in the graph

[Intel Mobile.sgrd.txt](https://github.com/lestofante/ksysguard-gpu/files/3666981/Intel.Mobile.sgrd.txt)
