### ISSUE TITLE
System freeze on arch linux

### ISSUE THREAD

**Issue by luisdralves** [lestofante/ksysguard-gpu#4]
I'm not sure if I didn't follow the instructions properly, but after installing, my system froze after boot. Here are some more details [https://bbs.archlinux.org/viewtopic.php?pid=1865628](url). Just thought I should let you know

**Comment by lestofante** [comment]
that is very interesting, could you try to just run the program that extrapolate the stat from your GPU?

for intel:
`intel_gpu_top -l`
for amd
`radeontop -t120 -d-`

if you have AMD, and the radeontop freeze your system, could you try to see if
`radeontop -d-`

does not hang the system?

**Comment by luisdralves** [comment]
It's as you suspect, both `radeontop -t120 -d-` and `radeontop -d-` freeze my system too. However, if I run `radeontop` without any parameters, it works fine and I get an interface.

**Comment by lestofante** [comment]
thanks for the update! Seems like more people are reporting freeze with radeontop, can you please check https://github.com/clbr/radeontop/issues/87

**Comment by luisdralves** [comment]
I'm sorry for the delay, I haven't paid much attention. I'll close the issue.

**Comment by lestofante** [comment]
no problem for the delay, ill reopen it so if someone will have the same issue he will know is still on-going and is from upstream radeontop

**Comment by BytEvil** [comment]
Hi, friends! I have same issue with radeontop on my Arch machine with conky (kernel 4.19.80-lts).
I use this command to grab gpu utilization every 5 sec.
`radeontop -d- -l1 -b1 | grep -o 'gpu [0-9]\{1,3\}' | cut -c 5-7`
System completely freeze after few days.

**Comment by lestofante** [comment]
Looks like fixed in recent kernel
