### ISSUE TITLE
Python executable header

### ISSUE THREAD

**Issue by pohzhiee** [lestofante/ksysguard-gpu#7]
The python header for this is `#!/bin/python3 -u` instead of the standard `#!/usr/bin/env python3`. For my system it results in the following error: 
`bash: ./gpuStatsServer.py: /bin/python3: bad interpreter: No such file or directory`

I strongly recommend changing to the standard header. See the relevant stackoverflow issue [here](https://stackoverflow.com/questions/3128669/python-script-header)

**Comment by lestofante** [comment]
closing as fixed in develop
